---
title: "UO Happiness Retreat Outcome Survey"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

<style type="text/css">

.sidebar {
  font-size: 1.5rem
}

</style>


```{r setup, include=FALSE}
library(flexdashboard)
library("dplyr")
library("tidyverse")
library("rio")
library("here")
library("forcats")
library("fivethirtyeight")
library("wesanderson")
library("ggplot2")
library("gdata")
library("viridis")
library("colorblindr")
library("stringr")
library("tidytext")
library("kableExtra")
library("formattable")
library("flextable")
library(emojifont)
library(devtools)

theme_set(theme_minimal(base_size = 8))
```

# Demographics {data-icon="fa-users"} 

Sidebar Title {.sidebar}
--------
These visualizations are based on the exit surveys from the past 4 Happiness Retreats at UO. Student health and wellness are important to success in life and academia. We are excited to continue spreading positivity across campus. Updated 1/25/2020
`r emo::ji("star")` `r emo::ji("star2")` `r emo::ji("star")` 


Column {.tabset}
-----------------------------------------------------------------------


```{r participants1}
SKY <- import(here("data", "survey.xlsx"), setclass = "tbl_df") 

OH0 <- SKY %>% 
  group_by(Category, Gender) %>% 
  summarise(n=n()) 
  
ggplot(OH0, aes(x = fct_reorder(Category, n), n)) +
  geom_col(aes(fill = Gender),
           color = "white",
           alpha = 0.7) +
  scale_y_continuous(breaks = seq(0, 14, by = 1),
                     limits = c(0, 14)) +
  scale_fill_OkabeIto() +
  coord_flip(expand = FALSE) +
  labs(x = "",
       y = "Number of participants",
       title = "Participant Distribution") +
  theme_minimal(base_size = 15)  + 
  theme(panel.grid.minor = element_line(linetype = "blank")) +
  guides(fill = "none")+
  geom_text(data = OH0[1,], aes(label = Gender), hjust = 1, color = "gray40")+
  geom_text(data = OH0[2,], aes(label = Gender), hjust = 2, color = "gray40")

```



# Experience {data-icon="fa-crown"} 

Sidebar Title {.sidebar}
--------
These visualizations are based on the exit surveys from the past 4 Happiness Retreats at UO. Student health and wellness are important to success in life and academia. We are excited to continue spreading positivity across campus. Updated 1/25/2020
`r emo::ji("star")` `r emo::ji("star2")` `r emo::ji("star")` 


Column {.tabset}
-----------------------------------------------------------------------



```{r f}

experience <- c("I thought it was positive and powerful",
                "It was very beautiful. It felt like truth",
                "Fantastic growth experience",
                "Wonderful! There were physically challenging moments while sitting for Sudarshan Kriya but I benefited a lot & have smiled more during this retreat than I have in a month",
                "I had a wonderful experience. I had been feeling very unbalanced and uncertain. I now feel much better and more centered",
                "I feel empowered and enlightened",
                "Very positive! Uplifting. Beautiful. Meaningful",
                "Great! I feel more relaxed, confident & can concentrate more on what I am doing",
                "So positive! I feel more capable of managing the things that come my way, and more open to others",
                "It was enlightening and freeing",
                "It was completely transformative. I LOVED it and felt so grateful for Sarah and Ting-fen and all their knowledge",
                "Wonderful!",
                "Kind. Open. Good experience",
                "Very positive, nurturing, and invigorating",
                "Nice. Learned so many new things",
                "Very positive and good use of time",
                "Amazing! So calming, welcoming, and educational",
                "Pretty amazing",
                "Amazing",
                "I enjoyed it",
                "It was great",
                "Calming effect, immediate change in how to deal with my life. Exciting to learn everything. Opening",
                "It was my first time attending SKY Happiness Retreat. I felt great, new and satisfied after this progress. Sara and Ting-fen shared their wisdom of how to live a happier and more peaceful life and how to attain a joyful state of mind. I am grateful for what I've learned from them",
                "Life changing. The breathing exercises really have helped center me",
                "Amazing",
                "Wonderful",
                "Exciting and grounding",
                "Needed",
                "It was an open and calm experience that helped with my anxiety")

experience_df <- tibble(line = 1:29, text = experience)

experience_df <- experience_df %>%
  unnest_tokens(word, text)

data(stop_words)

experience_df <- experience_df %>%
  anti_join(stop_words) %>% 
  filter(word != "feel" & word != "experience" & word != "ting" & word != "time" 
         & word != "fen" & word != "learned" & word != "life" & word != "retreat"
         & word != "experience")

 #experience_df %>%
 #count(word, sort = TRUE) 


experience_df  %>%
  count(word, sort = TRUE) %>%
  filter (n > 1) %>%
  mutate(word = str_to_title(word),
         word = reorder(word, n)) %>%
  ggplot(aes(word, n)) +
  geom_col(fill = "cornflowerblue",
           alpha = 0.7) +
  scale_y_continuous(breaks = seq(0, 20, by = 1),
                     limits = c(0, 5.25)) +
  xlab(NULL) +
  coord_flip() + 
  coord_flip(expand = FALSE) +
  labs(x = "",
       y = "Word Frequency Count",
       title = "How was the experience?") +
    theme_minimal(base_size = 15)  + 
    theme_minimal(base_size = 15)  + 
  theme(panel.grid.minor = element_line(linetype = "blank")) +
  guides(fill = "none") 


```



# More {data-icon="fa-grin-stars"} 

Sidebar Title {.sidebar}
--------
These visualizations are based on the exit surveys from the past 4 Happiness Retreats at UO. Student health and wellness are important to success in life and academia. We are excited to continue spreading positivity across campus. Updated 1/25/2020
`r emo::ji("star")` `r emo::ji("star2")` `r emo::ji("star")` 

Column {.tabset}
-----------------------------------------------------------------------


```{r table}

SKY <- import(here("data", "survey.xlsx"), setclass = "tbl_df") 

# SKY %>%
#   count(energy) %>%
#   mutate(prop = 100*n/sum(n-1))
# 
# SKY %>%
#   count(clarity_mind) %>%
#   mutate(prop = 100*n/sum(n-1))
# 
# SKY %>%
#   count(multiple_responsibilities) %>%
#   mutate(prop = 100*n/sum(n-1))
# 
# SKY %>%
#   count(connect_to_myself) %>%
#   mutate(prop = 100*n/sum(n-1))
# 
# SKY %>%
#   count(stay_focused) %>%
#   mutate(prop = 100*n/sum(n-1))
# 
# SKY %>%
#   count(remain_calm) %>%
#   mutate(prop = 100*n/sum(n-1))
# 
# SKY %>%
#   count(gain_resilience) %>%
#   mutate(prop = 100*n/sum(n-1))
# 
# 
# SKY %>%
#   count(broader_perspectives) %>%
#   mutate(prop = 100*n/sum(n-1))
# 
# SKY %>%
#   count(connect_with_others) %>%
#   mutate(prop = 100*n/sum(n-1))



SKY2 <- import(here("data", "SKY2.xlsx"), setclass = "tbl_df") 

SKY2 %>% 
  kable(caption = "The SKY Happiness Retreat impacts various domains of life. Numbers are in percentages.") %>% 
   kable_styling(bootstrap_options = c("striped", "hover", "condensed", "responsive", full_width = NULL, position = "left")) %>% 
  column_spec(6:6, bold = T, color = "#3A9E23", background = "#F8F668") %>%
   footnote(general = "The participants were asked to rate how the techniques taught in the SKY Happiness Retreat have the ability to impact different areas.")

```





# Recommend {data-icon="fa-thumbs-up"} 

Sidebar Title {.sidebar}
--------
These visualizations are based on the exit surveys from the past 4 Happiness Retreats at UO. Student health and wellness are important to success in life and academia. We are excited to continue spreading positivity across campus. Updated 1/25/2020
`r emo::ji("star")` `r emo::ji("star2")` `r emo::ji("star")` 


Column {.tabset}
-----------------------------------------------------------------------


```{r recommend1}

SKY <- import(here("data", "survey.xlsx"), setclass = "tbl_df") 

ggplot(SKY, aes(Recommend)) +
  geom_dotplot(aes(fill = Category), 
               stackgroups = TRUE,
               binwidth = .3) +
  scale_fill_OkabeIto(name = "") +
  scale_x_continuous(breaks = 0:6, limits = c(0, 6),
                     labels=c("0" = "", 
                              "1" = "Strongly Disagree",
                              "2" = "Disagree", 
                              "3" = "Neutral",
                              "4" = "Agree", 
                              "5" = "Strongly Agree",
                              "6" = "")) +
  scale_y_continuous(labels=c("0.00" = "0", 
                              "0.25" = "7",
                              "0.50" = "14", 
                              "0.75" = "21",
                              "1.00" = "28")) +
   coord_flip(expand = FALSE) +
   theme_minimal(base_size = 10) +
  theme(panel.grid.minor = element_line(linetype = "blank")) +
  labs(x = NULL, 
       y = NULL, 
       title = "Here is how the participants feel about",
       subtitle = "recommending this Retreat to their peers")+
  labs(y = "Number of Participants") +
  theme(legend.position = "bottom")
```



